worker_processes 1;
pid /run/nginx.pid;

events {
    worker_connections 512;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    error_log /dev/stderr;
    sendfile on;

    server {
        listen 8080;
        root /site/_site;
        index index.html;

        location / {
            try_files $uri $uri/ $uri/index.html =404;
        }
    }
}
